[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r backend/requirements.txt'
]

[start]
cmd = 'cd backend && python run.py'