[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r backend/requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'python backend/run.py'