[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python run.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9"